#!/bin/bash

if [ "$#" = 0 ]; then
    echo "Usage: run0 pacman-bootc remove <options> <package>"
    echo "Options:"
    echo "--keep-etc   don't touch /etc"
    exit 1
fi

KEEP_ETC=false

while [[ "$1" =~ ^- ]]; do
    case "$1" in
        --keep-etc) KEEP_ETC=true ;;
        *)     break ;;
    esac
    shift
done

PKG=$1
FILE="/var/lib/extensions/$PKG.raw"
SUBVOL_DIR="/var/lib/extensions/$PKG"

if [[ -f "/usr/lib/pacman-bootc/pkgs/$PKG" && "$KEEP_ETC" = false ]]; then
    tac "/usr/lib/pacman-bootc/pkgs/$PKG" | while read -r file; do
        [ -z "$file" ] && continue
        rm -fd "$file" 2>/dev/null
    done
fi

if [ -d "$SUBVOL_DIR" ]; then
    # btrfs sysext
    systemd-sysext unmerge &> /dev/null
    echo "-> Removing package: $SUBVOL_DIR"
    btrfs subvolume delete "$SUBVOL_DIR" &> /dev/null
    if [ -d "$SUBVOL_DIR" ]; then
        rm -rf "$SUBVOL_DIR"
    fi

elif [ -f "$FILE" ]; then
    #.raw sysext
    systemd-sysext unmerge &> /dev/null
    echo "-> Removing package: $FILE"
    rm "$FILE"

else
    echo "Error: '$PKG' is not installed!"
    exit 1
fi

systemd-sysext merge &> /dev/null
systemctl reload dbus

echo "✓ Package removed!"
