#!/bin/bash

EXT_DIR="/var/lib/extensions"

if [ -d "$EXT_DIR" ] && ls "$EXT_DIR"/*.raw &>/dev/null; then
    echo ""
    echo "-> Reseting system image (removing sysexts)."

    for file in "$EXT_DIR"/*.raw; do
        PKG=$(basename "$file" .raw)

        echo "-> Removing $PKG"
        "./pacman-bootc-remove" "$PKG" &>/dev/null
    done

    echo "✓ System was reset!"
else
    echo "No sysext found"
fi
