#!/bin/bash

if [ "$#" = 0 ]; then
    echo "Usage: run0 pacman-bootc install <options> <package> <additional packages>"
    echo "Options:"
    echo "--refresh    refresh repos"
    echo "--keep-etc   don't touch /etc"
    echo "--raw        install package as .raw image"
    echo "-y           skip confirmation promtps"
    exit 1
fi

KEEP_ETC=false

while [[ "$1" =~ ^- ]]; do
    case "$1" in
        --refresh) REFRESH=true ;;
        --keep-etc) KEEP_ETC=true ;;
        --raw) USE_RAW=true ;;
        --noconfirm)   NOCONFIRM=true ;;
        -y)   NOCONFIRM=true ;;
        *)     break ;;
    esac
    shift
done

PKG=$1
EXT_DIR="/var/lib/extensions"
WORK_DIR=$(mktemp -d)
CACHE_DIR="$WORK_DIR/cache"
TMP_DB=$(mktemp -d)
HAS_DOWNLOADED=false

PKGS_INSTALL=("$@")

if [ -z "$PKG" ]; then
    echo "No packages to install!" >&2
    exit 1
fi

cp -rp /usr/lib/sysimage/lib/pacman/* "$TMP_DB/" || true
mkdir -p "$CACHE_DIR"
mkdir -p "$WORK_DIR/usr"

if [ "$REFRESH" = true ]; then
    echo "-> Refreshing repos..."
    pacman --dbpath "$TMP_DB" -Syy --cachedir "$CACHE_DIR"
fi

echo "-> Downloading packages..."
if [ "$NOCONFIRM" = true ]; then
    pacman --dbpath "$TMP_DB" -Sw --needed --noconfirm --cachedir "$CACHE_DIR" "${PKGS_INSTALL[@]}"
else
    pacman --dbpath "$TMP_DB" -Sw --needed --cachedir "$CACHE_DIR" "${PKGS_INSTALL[@]}"
fi

if [ $? -ne 0 ]; then
    rm -rf "$CACHE_DIR" "$TMP_DB"
    exit 1
fi

for archive in "$CACHE_DIR"/*.pkg.tar.zst; do
    [ -e "$archive" ] || continue
    if [ "$HAS_DOWNLOADED" = false ]; then
        echo "-> Extracting packages..."
    fi
    HAS_DOWNLOADED=true
    echo "   Extracting: $(basename "$archive")"
    tar --use-compress-program=unzstd -xf "$archive" -C "$WORK_DIR" --strip-components=0
done
rm -rf "$CACHE_DIR"

if [ "$HAS_DOWNLOADED" = false ]; then
    rm -rf "$WORK_DIR" "$TMP_DB"
    exit 0
fi

# Compile gschemas
SCHEMA_DIR="$WORK_DIR/usr/share/glib-2.0/schemas"
if [ -d "$SCHEMA_DIR" ]; then
    glib-compile-schemas "$SCHEMA_DIR"
fi

# Move etc
mkdir "$WORK_DIR/usr/etc"
cp -r "$WORK_DIR/etc" "$WORK_DIR/usr"
mkdir -p "$WORK_DIR/usr/lib/pacman-bootc/pkgs"
touch "$WORK_DIR/usr/lib/pacman-bootc/pkgs/$PKG"
(cd "$WORK_DIR/etc" && find . -mindepth 1 | sed 's|^\.|/etc|') >> "$WORK_DIR/usr/lib/pacman-bootc/pkgs/$PKG"

if [ "$KEEP_ETC" = false ]; then
    cp -r "$WORK_DIR/etc" "/"
fi

if [ "$USE_RAW" = true ]; then
    # Generate .raw sysext
    mkdir -p "$WORK_DIR/usr/lib/extension-release.d"
cat <<EOF > "$WORK_DIR/usr/lib/extension-release.d/extension-release.$PKG"
ID=arch
VERSION_ID=rolling
EOF

    echo "-> Generating sysext"
    mkdir -p "$EXT_DIR"
    mksquashfs "$WORK_DIR" "$EXT_DIR/$PKG.raw" -noappend -comp zstd &> /dev/null
else
    # Generate btrfs sysext
    FINAL_DEST="$EXT_DIR/$PKG"
    if [ -d "$FINAL_DEST" ]; then
        btrfs subvolume delete "$FINAL_DEST" &> /dev/null || rm -rf "$FINAL_DEST"
    fi

    echo "-> Generating sysext"
    btrfs subvolume create "$FINAL_DEST"

    cp -rp "$WORK_DIR"/. "$FINAL_DEST/"
    mkdir -p "$FINAL_DEST/usr/lib/extension-release.d"
cat <<EOF > "$FINAL_DEST/usr/lib/extension-release.d/extension-release.$PKG"
ID=arch
VERSION_ID=rolling
EOF
fi

systemd-sysext refresh &> /dev/null
ldconfig &> /dev/null
systemctl reload dbus

echo "-> Package installed!"
rm -rf "$WORK_DIR"
rm -rf "$TMP_DB"
