set quiet := true
import '/usr/share/spacefin/setups.just'
import '/usr/share/spacefin/utilities.just'

[group("system")]
battery:
    upower -i /org/freedesktop/UPower/devices/battery_BAT0

[group("system")]
cleanup:
    run0 podman image prune -af
    run0 podman volume prune -f
    podman image prune -af
    podman volume prune -f
    flatpak uninstall --unused
    brew autoremove
    brew cleanup

[group("system")]
reset-niri-config:
    rm -r ~/.config/niri/
    rm ~/.config/ghostty/config
    cp -r /etc/skel/.config/niri/ ~/.config/
    cp /etc/skel/.config/ghostty/config ~/.config/ghostty/

[group("system")]
bios:
    #!/usr/bin/bash
    if [ -d /sys/firmware/efi ]; then
        read -rp 'The system will reboot into UEFI firmware settings. Proceed? (y/N) ' proceed
        if [[ "$proceed" == [Yy]* ]]; then
            systemctl reboot --firmware-setup
        fi
    else
        echo "Rebooting to legacy BIOS from OS is not supported."
    fi

[group("system")]
check-local-overrides:
    #!/usr/bin/bash
    RESET="\x1b[0m"
    if [ "${NO_COLOR}" == 1 ]; then
        BLUE_COLOR=""
        GREEN_COLOR=""
        YELLOW_COLOR=""
    else
        BLUE_COLOR="${BLUE_COLOR:-\x1b[38;5;117m}"
        GREEN_COLOR="${GREEN_COLOR:-\x1b[38;5;85m}"
        YELLOW_COLOR="${YELLOW_COLOR:-\x1b[93m}"
    fi

    diff -qr \
      --suppress-common-lines \
      --color="always" \
      --exclude "passwd*" \
      --exclude "group*" \
      --exclude="subgid*" \
      --exclude="subuid*" \
      --exclude="machine-id" \
      --exclude="adjtime" \
      --exclude="fstab" \
      --exclude="system-connections" \
      --exclude="shadow*" \
      --exclude="gshadow*" \
      --exclude="ssh_host*" \
      --exclude="cmdline" \
      --exclude="crypttab" \
      --exclude="hostname" \
      --exclude="localtime" \
      --exclude="locale*" \
      --exclude="*lock" \
      --exclude=".updated" \
      --exclude="*LOCK" \
      --exclude="vconsole*" \
      --exclude="00-keyboard.conf" \
      --exclude="grub" \
      --exclude="system.control*" \
      --exclude="cdi" \
      --exclude="default.target" \
      /usr/etc /etc 2>/dev/null | sed \
          -e '/Binary\ files\ /d ; /Common subdirectories/d' \
          -e "/Files/ s/^/${BLUE_COLOR}&/g" \
          -e "/Files/ s/\$/&${RESET}/g" \
          -e "/Only in/ s/^/${GREEN_COLOR}&/g" \
          -e "/Only in/ s/\$/&${RESET}/g" \
          -e "s/\:.*/${RESET}${YELLOW_COLOR}&${RESET}/g"

[group("system")]
logs-this-boot:
    run0 journalctl -b 0

[group("system")]
logs-last-boot:
    run0 journalctl -b -1

[group("system")]
update:
    /usr/share/spacefin/scripts/update.sh

[group('DOOM')]
powerwash:
    #!/usr/bin/bash
    if command -v bctl &>/dev/null; then
        exec bctl powerwash
    fi

    echo "Warning: This is an experimental feature that will reset this device to its factory state."
    read -p "Do you want to continue? (y/N): " CONFIRM
    if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
        echo "Powerwash cancelled."
        exit 0
    fi
    read -p "Are you sure? (y/N): " CONFIRM2
    if [[ ! "$CONFIRM2" =~ ^[Yy]$ ]]; then
        echo "Powerwash cancelled."
        exit 0
    fi

    sudo bootc install reset --experimental
